twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'form/theme.html.twig' ]
    globals:
        helper: '@App\Util\TwigHelper'

when@test:
    twig:
        strict_variables: true
